### ISSUE TITLE
Bunker Issue

### ISSUE THREAD

**Issue by ConfusedCoder85** [JavaScythe/Bunker#30]
Bruhhost for assorted games no longer works
(for right now switch to github.io and play. Only works for some games)

**Comment by ConfusedCoder85** [comment]
Never mind. Switch to v6-fixhost.

**Comment by mathadventure1** [comment]
good to know its fixed

**Comment by JavaScythe** [comment]
Like the original message said, this is why different game providers were implemented.
v6-fixhost was released minutes after I took the original game host offline (vercel was going to disable domain because 0.77 million requests!)
v7 will obviously introduce auto updates, which will help address these time sensitive fixes

**Comment by mathadventure1** [comment]
:chadface:
