### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Viberiouss** [JavaScythe/Bunker#34]
How do we compile the source code into a working file?

**Comment by Cattn** [comment]
This source code when compiled will not be the same as the mainstream releases, if you are looking for the compiled files you can find those in the releases tab. If you want to checkout betas you can do that in the discord: discord.gg/mathstudy by getting the beta role

Also to he honest the compiler isn't user friendly and doesn't work for most

If you want to try, make sure you exclude the proper files and install node js, dree, and then try and run compiler.js through npm

Otherwise we will be updating the compiler soon to make it more user friendly and clearer

**Comment by Viberiouss** [comment]
Yeah I just edited the source code a bit and I wondered how to make the file the same as yours.

**Comment by Cattn** [comment]
Yep compiler will be much more friendly + actually work soon (before next update probably)

**Comment by Viberiouss** [comment]
Wait, is there a way to get the compiled files as released that's not the source code?

**Comment by JavaScythe** [comment]
Look under the releases page
https://github.com/javascythe/bunker/releases
