### ISSUE TITLE
Not hiding from extensions correctly

### ISSUE THREAD

**Issue by In33dh3lp** [JavaScythe/Bunker#40]
Go gaurdian can still access and block stuff on the page even thought it says its hiding from extentions, if anyone here still answers these i guess

**Comment by JavaScythe** [comment]
GoGuardian can't:
- See content (text and images) on Bunker
- Inject itself into Bunker
GoGuardian CAN:
- Inject itself into external iframes (e.g. example.com in a frame on bunker)
- Block requests from Bunker (which is why sites you enter into the Iframer can still be blocked

In short, this is normal and expected behavior.

btw, bunker is now obsolete. It still (somewhat) works, but that's it.
